# Generated by Django 4.0.6 on 2022-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
